# Generated by Django 3.2.12 on 2023-02-06 06:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('subtitle', models.CharField(max_length=255, verbose_name='Subtitle')),
                ('content', models.TextField(verbose_name='Content')),
                ('date_published', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('author', models.CharField(max_length=255, verbose_name='Autor')),
                ('catergory1', models.CharField(blank=True, max_length=255, verbose_name='Category1')),
                ('catergory2', models.CharField(blank=True, max_length=255, verbose_name='Category2')),
                ('catergory3', models.CharField(blank=True, max_length=255, verbose_name='Category3')),
                ('tag1', models.CharField(blank=True, max_length=255, verbose_name='Tag1')),
                ('tag2', models.CharField(blank=True, max_length=255, verbose_name='Tag2')),
                ('tag3', models.CharField(blank=True, max_length=255, verbose_name='Tag3')),
                ('tag4', models.CharField(blank=True, max_length=255, verbose_name='Tag4')),
                ('tag5', models.CharField(blank=True, max_length=255, verbose_name='Tag5')),
                ('tag6', models.CharField(blank=True, max_length=255, verbose_name='Tag6')),
                ('tag7', models.CharField(blank=True, max_length=255, verbose_name='Tag7')),
                ('tag8', models.CharField(blank=True, max_length=255, verbose_name='Tag8')),
                ('tag9', models.CharField(blank=True, max_length=255, verbose_name='Tag9')),
                ('tag10', models.CharField(blank=True, max_length=255, verbose_name='Tag10')),
                ('read_count', models.IntegerField(default=0, verbose_name='Read Count')),
            ],
        ),
        migrations.CreateModel(
            name='BlogPostAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
