# Generated by Django 3.2.12 on 2023-02-07 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='picture_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Picture_name'),
        ),
    ]
