# Generated by Django 3.2.12 on 2023-02-08 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_picture_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='catergory1',
            new_name='category1',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='catergory2',
            new_name='category2',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='catergory3',
            new_name='category3',
        ),
    ]
