# Generated by Django 3.2.12 on 2023-02-08 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20230208_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='quotes',
            field=models.CharField(blank=True, max_length=255, verbose_name='Quatation'),
        ),
    ]
