# Generated by Django 3.2.12 on 2023-02-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogpost_quotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='content2',
            field=models.TextField(blank=True, verbose_name='Content2'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(verbose_name='Content1'),
        ),
    ]
